# Generated by Django 4.2.9 on 2024-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('c', 'Em casa'), ('p', 'Perdido'), ('E', 'Emprestado')], max_length=1)),
            ],
        ),
    ]
